In [1]:
#import dependencies
import pandas as pd

In [2]:
#read in dataset
csv_path = "Resources/AllTrails_data_nationalpark.csv"
all_trails_df = pd.read_csv(csv_path)
all_trails_df.head()

,trail_id,name,area_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,3.0,5.0,423,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'camping', 'hiking', 'nature-trips...",i
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,1.0,4.5,260,"['dogs-no', 'forest', 'views', 'wild-flowers',...","['birding', 'camping', 'hiking', 'nature-trips...",i
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,3.0,4.5,224,"['dogs-no', 'partially-paved', 'views', 'wildl...","['hiking', 'walking']",i
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,2.0,4.5,237,"['dogs-no', 'forest', 'lake', 'kids', 'views',...","['birding', 'hiking', 'nature-trips', 'trail-r...",i
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,1.0,4.5,110,"['dogs-no', 'lake', 'views', 'wild-flowers', '...","['birding', 'fishing', 'hiking', 'nature-trips...",i

In [4]:
#review visitor_usage for min and max
all_trails_df['visitor_usage'].describe()
print(visitor_usage)

count    3060.000000
mean        1.877124
std         0.693641
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         4.000000
Name: visitor_usage, dtype: float64

In [5]:
#review trail name value counts and length
all_trails_df['name'].value_counts()

Black Canyon Trail                                                                             3
Horseshoe Lake Trail                                                                           2
Dege Peak Trail                                                                                2
Dream Lake Trail                                                                               2
Grand View Point Trail                                                                         2
                                                                                              ..
Ernst Tinaja Trail                                                                             1
Trans Sierra Trip: Colby Pass Trail, High Sierra Trail, John Muir Trail, Mount Whitney, PCT    1
Crest View Trail                                                                               1
Hightop Peak Trail                                                                             1
Abrams Falls Via Abrams Creek Campground                                                       1
Name: name, Length: 3288, dtype: int64

In [8]:
#review country name since this is supposed to be a US National Park dataset 
all_trails_df['country_name'].value_counts()

United States    3264
Hawaii             49
Name: country_name, dtype: int64

In [9]:
#reive state names with value counts
all_trails_df['state_name'].value_counts()

California        707
Washington        320
Wyoming           311
Utah              292
Colorado          262
Virginia          191
Maine             179
Tennessee         175
Arizona           174
Montana           151
North Carolina    118
Texas              94
Ohio               50
Hawaii             35
Florida            31
Alaska             29
Kentucky           28
Nevada             25
North Dakota       23
Oregon             22
South Dakota       20
Arkansas           16
Indiana            16
Maui               14
New Mexico          8
South Carolina      8
Minnesota           7
Michigan            4
Missouri            2
Georgia             1
Name: state_name, dtype: int64

In [11]:
#review park names and unique length
area_unique = all_trails_df['area_name'].unique()
print(len(area_unique))
area_unique

60

array(['Kenai Fjords National Park', 'Denali National Park',
       'Glacier Bay National Park', 'Katmai National Park',
       'Grand Canyon National Park', 'Saguaro National Park',
       'Petrified Forest National Park', 'Hot Springs National Park',
       'Yosemite National Park', 'Sequoia National Park',
       'Joshua Tree National Park', 'Lassen Volcanic National Park',
       'Kings Canyon National Park', 'Pinnacles National Park',
       'Death Valley National Park', 'Redwood National Park',
       'Channel Islands National Park', 'Rocky Mountain National Park',
       'Great Sand Dunes National Park and Preserve',
       'Mesa Verde National Park',
       'Black Canyon of the Gunnison National Park',
       'Everglades National Park', 'Fort Pickens National Park',
       'Biscayne National Park', 'Dry Tortugas National Park',
       'Clayton Co International Park, Jonesboro GA',
       'Indiana Dunes National Park', 'Mammoth Cave National Park',
       'Acadia National Park', 'Isle Royale National Park',
       'Voyageurs National Park', 'Gateway Arch National Park',
       'Glacier National Park', 'Yellowstone National Park',
       'Great Basin National Park', 'Carlsbad Caverns National Park',
       'Great Smoky Mountains National Park',
       'Theodore Roosevelt National Park',
       'Cuyahoga Valley National Park', 'Crater Lake National Park',
       'Congaree National Park', 'Congaree National Park Wilderness',
       'Badlands National Park', 'Wind Cave National Park',
       'Guadalupe Mountains National Park', 'Big Bend National Park',
       'Zion National Park', 'Arches National Park',
       'Bryce Canyon National Park', 'Canyonlands National Park',
       'Capitol Reef National Park', 'Shenandoah National Park',
       'Fort Hunt National Park',
       'Wolf Trap National Park for the Performing Arts',
       'Mount Rainier National Park', 'Olympic National Park',
       'North Cascades National Park', 'Grand Teton National Park',
       'Hawaii Volcanoes National Park', 'Haleakala National Park'],
      dtype=object)

In [14]:
#review features with value_counts and length
all_trails_df['features'].value_counts()

['dogs-no', 'forest', 'views', 'wild-flowers', 'wildlife']                                                     175
['dogs-no', 'views', 'wild-flowers', 'wildlife']                                                               121
['dogs-no', 'views']                                                                                           114
['dogs-no', 'forest', 'lake', 'views', 'wild-flowers', 'wildlife']                                             103
['dogs-no', 'forest', 'river', 'views', 'wild-flowers', 'wildlife']                                             78
                                                                                                              ...
['dogs-no', 'kids', 'river', 'views', 'waterfall']                                                               1
['dogs-leash', 'forest', 'lake', 'views', 'wild-flowers']                                                        1
['dogs-no', 'forest', 'kids', 'partially-paved', 'river', 'views', 'waterfall', 'wild-flowers', 'wildlife']      1
['beach', 'dogs-no', 'kids', 'wildlife']                                                                         1
['lake', 'kids', 'river', 'views']                                                                               1
Name: features, Length: 744, dtype: int64

In [15]:
#review activities with value_counts and length; notice difference between 744 for features and 526 for activities
all_trails_df['activities'].value_counts()

['birding', 'hiking', 'nature-trips', 'walking']                                                                                       450
['birding', 'hiking', 'nature-trips', 'trail-running', 'walking']                                                                      249
['birding', 'hiking', 'nature-trips']                                                                                                  189
['hiking']                                                                                                                             156
['hiking', 'nature-trips', 'walking']                                                                                                  127
                                                                                                                                      ...
['backpacking', 'birding', 'walking']                                                                                                    1
['backpacking', 'hiking', 'nature-trips', 'trail-running', 'walking', 'horseback-riding']                                                1
['backpacking', 'camping', 'fishing', 'hiking', 'paddle-sports', 'trail-running', 'whitewater-kayaking', 'fly-fishing', 'canoeing']      1
['birding', 'fishing', 'hiking', 'nature-trips', 'rock-climbing', 'snowshoeing', 'trail-running', 'walking', 'fly-fishing']              1
['hiking', 'nature-trips', 'off-road-driving', 'walking']                                                                                1
Name: activities, Length: 526, dtype: int64

In [36]:
#after discussing the review of this dataset; agree to drop specific columns
clean_all_trails = all_trails_df.drop(columns=['city_name', 'country_name', 'units', 'visitor_usage', 'features', 'activities'])
clean_all_trails.head()

,trail_id,name,area_name,state_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,5.0,423
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,4.5,260
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,4.5,224
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,4.5,237
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,4.5,110

In [37]:
#After further review of national parks, google results inform me that this Clayton Co International is not a national park.
print(clean_all_trails[clean_all_trails['area_name']=="Clayton Co International Park, Jonesboro GA"])

      trail_id                                     name  \
1219  10259207  Clayton County International Park Trail

                                        area_name state_name  \
1219  Clayton Co International Park, Jonesboro GA    Georgia

                                 _geoloc  popularity    length  \
1219  {'lat': 33.5312, 'lng': -84.31568}      4.7291  2574.944

      elevation_gain  difficulty_rating route_type  avg_rating  num_reviews
1219         36.8808                  3       loop         4.0           26

In [38]:
#dropping row with Clayton Co International Park by index
clean_all_trails.drop([1219], inplace = True)

In [39]:
#Leah found this code to help split the _geoloc column
lat = []
lon = []
# For each row in a varible,
for row in clean_all_trails['_geoloc']:
    # Try to,
    try:
        # Split the row by comma and append
        # everything before the comma to lat
        lat.append(row.split(',')[0])
        # Split the row by comma and append
        # everything after the comma to lon
        lon.append(row.split(',')[1])
    # But if you get an error
    except:
        # append a missing value to lat
        lat.append(np.NaN)
        # append a missing value to lon
        lon.append(np.NaN)
# Create two new columns from lat and lon
clean_all_trails['trailhead_lat'] = lat
clean_all_trails['trailhead_long'] = lon

In [40]:
#dropping _geoloc now that we have trailhead_lat and trailhead_long
clean_all_trails = clean_all_trails.drop(columns=['_geoloc'])
clean_all_trails.head()

,trail_id,name,area_name,state_name,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.8931,15610.598,1161.8976,5,out and back,5.0,423,{'lat': 60.18852,'lng': -149.63156}
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0311,6920.162,507.7968,3,out and back,4.5,260,{'lat': 63.73049,'lng': -148.91968}
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.7821,2896.812,81.9912,1,out and back,4.5,224,{'lat': 60.18879,'lng': -149.631}
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.2674,3379.614,119.7864,1,loop,4.5,237,{'lat': 63.73661,'lng': -148.915}
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.5935,29772.790,1124.7120,5,out and back,4.5,110,{'lat': 63.73319,'lng': -148.89682}

In [41]:
#dataframe before next step
clean_trails_df = pd.DataFrame(clean_all_trails)
clean_trails_df.head()

,trail_id,name,area_name,state_name,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.8931,15610.598,1161.8976,5,out and back,5.0,423,{'lat': 60.18852,'lng': -149.63156}
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0311,6920.162,507.7968,3,out and back,4.5,260,{'lat': 63.73049,'lng': -148.91968}
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.7821,2896.812,81.9912,1,out and back,4.5,224,{'lat': 60.18879,'lng': -149.631}
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.2674,3379.614,119.7864,1,loop,4.5,237,{'lat': 63.73661,'lng': -148.915}
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.5935,29772.790,1124.7120,5,out and back,4.5,110,{'lat': 63.73319,'lng': -148.89682}

In [42]:
#Leah's help with further cleaning these columns
cleaning_lat = {
    "{'lat':": ""
}

clean_trails_df = clean_trails_df.replace(cleaning_lat, regex=True)
clean_trails_df['trailhead_lat'] = clean_trails_df['trailhead_lat'].str.strip()

clean_trails_df.head()

,trail_id,name,area_name,state_name,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.8931,15610.598,1161.8976,5,out and back,5.0,423,60.18852,'lng': -149.63156}
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0311,6920.162,507.7968,3,out and back,4.5,260,63.73049,'lng': -148.91968}
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.7821,2896.812,81.9912,1,out and back,4.5,224,60.18879,'lng': -149.631}
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.2674,3379.614,119.7864,1,loop,4.5,237,63.73661,'lng': -148.915}
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.5935,29772.790,1124.7120,5,out and back,4.5,110,63.73319,'lng': -148.89682}

In [43]:
cleaning_lon = {
    "'lng':": "",
    "}": ""
}
clean_trails_df = clean_trails_df.replace(cleaning_lon, regex=True)
clean_trails_df['trailhead_long'] = clean_trails_df['trailhead_long'].str.strip()

clean_trails_df.head()

,trail_id,name,area_name,state_name,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.8931,15610.598,1161.8976,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0311,6920.162,507.7968,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.7821,2896.812,81.9912,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.2674,3379.614,119.7864,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.5935,29772.790,1124.7120,5,out and back,4.5,110,63.73319,-148.89682

In [44]:
#renaming columns to match schema
clean_trails_df = clean_trails_df.rename(columns={"name": "trail_name",
                                                    "area_name": "national_park",
                                                    "state_name": "state",
                                                    "elevation_gain": "elevation",
                                                    "difficulty_rating": "difficulty",
                                                    "route_type": "route_type",
                                                    "avg_rating": "rating",
                                                   })
clean_trails_df.head()

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.8931,15610.598,1161.8976,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0311,6920.162,507.7968,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.7821,2896.812,81.9912,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.2674,3379.614,119.7864,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.5935,29772.790,1124.7120,5,out and back,4.5,110,63.73319,-148.89682

In [45]:
#rounding popularity
clean_trails_df['popularity'] = clean_trails_df['popularity'].round(1)
popularity_stats = clean_trails_df['popularity'].describe()
print(popularity_stats)
clean_trails_df.head()

count    3312.000000
mean        8.955193
std         8.139165
min         0.000000
25%         3.800000
50%         6.600000
75%        11.300000
max        84.600000
Name: popularity, dtype: float64

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.9,15610.598,1161.8976,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0,6920.162,507.7968,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.8,2896.812,81.9912,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.3,3379.614,119.7864,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.6,29772.790,1124.7120,5,out and back,4.5,110,63.73319,-148.89682

In [46]:
#rounding elevation
clean_trails_df['elevation'] = clean_trails_df['elevation'].round(1)
elevation_stats = clean_trails_df['elevation'].describe()
print(elevation_stats)
clean_trails_df.head()

count     3312.000000
mean       641.988104
std        901.581984
min          0.000000
25%        117.675000
50%        360.450000
75%        834.375000
max      14029.900000
Name: elevation, dtype: float64

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.9,15610.598,1161.9,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0,6920.162,507.8,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.8,2896.812,82.0,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.3,3379.614,119.8,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.6,29772.790,1124.7,5,out and back,4.5,110,63.73319,-148.89682

In [48]:
#reviewing the length column
clean_trails_df['length'].describe()

count      3312.000000
mean      17681.408470
std       25499.875752
min           0.000000
25%        4506.152000
50%       10621.644000
75%       21404.222000
max      529794.728000
Name: length, dtype: float64

In [49]:
#moving decimal to make values in kilometers
clean_trails_df['length'] = clean_trails_df['length'].div(1000)
clean_trails_df.head()

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.9,15.610598,1161.9,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0,6.920162,507.8,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.8,2.896812,82.0,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.3,3.379614,119.8,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.6,29.772790,1124.7,5,out and back,4.5,110,63.73319,-148.89682

In [50]:
#changing length value of kilometers to miles
clean_trails_df['length'] = clean_trails_df['length'].div(1.609)
clean_trails_df.head()

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.9,9.702050,1161.9,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0,4.300909,507.8,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.8,1.800380,82.0,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.3,2.100444,119.8,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.6,18.503909,1124.7,5,out and back,4.5,110,63.73319,-148.89682

In [51]:
#rounding length
clean_trails_df['length'] = clean_trails_df['length'].round(1)
length_stats = clean_trails_df['length'].describe()
print(length_stats)
clean_trails_df.head()

count    3312.000000
mean       10.986775
std        15.845534
min         0.000000
25%         2.800000
50%         6.600000
75%        13.300000
max       329.300000
Name: length, dtype: float64

,trail_id,trail_name,national_park,state,popularity,length,elevation,difficulty,route_type,rating,num_reviews,trailhead_lat,trailhead_long
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Alaska,24.9,9.7,1161.9,5,out and back,5.0,423,60.18852,-149.63156
1,10236086,Mount Healy Overlook Trail,Denali National Park,Alaska,18.0,4.3,507.8,3,out and back,4.5,260,63.73049,-148.91968
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Alaska,17.8,1.8,82.0,1,out and back,4.5,224,60.18879,-149.631
3,10236076,Horseshoe Lake Trail,Denali National Park,Alaska,16.3,2.1,119.8,1,loop,4.5,237,63.73661,-148.915
4,10236082,Triple Lakes Trail,Denali National Park,Alaska,12.6,18.5,1124.7,5,out and back,4.5,110,63.73319,-148.89682

In [52]:
clean_trails_df.to_csv('Resources/clean_trails_df.csv', index=False, header=True)